spec-version: 0.30.0
name: grimoire
version:  0.0.1
author: Asad Saeeduddin
maintainer: masaeedu@gmail.com
license: MIT

build-type: Simple

dependencies:
- { name: "base", version: '>=4.14 && <4.15' }

ghc-options: -Wall
default-extensions:
- GADTs

- StandaloneDeriving
- DeriveFunctor
- DerivingVia
- GeneralizedNewtypeDeriving

- ScopedTypeVariables
- RankNTypes
- QuantifiedConstraints

- TypeApplications
- TypeOperators
- MultiParamTypeClasses

- ConstraintKinds
- DataKinds
- PolyKinds
- StandaloneKindSignatures

- UndecidableInstances
- FlexibleInstances
- FlexibleContexts
- DefaultSignatures

library:
  source-dirs: lib

tests:
  grimoire-spec:
    main: Main.hs
    source-dirs:
    - test
    dependencies:
    - grimoire
    - hspec
